"""
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
ISO 639 is a standardized nomenclature used to classify languages. Each language is
assigned a two-letter (639-1) and three-letter (639-2 and 639-3) lowercase
abbreviation, amended in later versions of the nomenclature.

This list contains all of:
ISO 639-1: two-letter codes, one per language for ISO 639 macrolanguage

And some of:
ISO 639-2/T: three-letter codes, for the same languages as 639-1.
ISO 639-2/B: three-letter codes, mostly the same as 639-2/T, but with some codes
derived from English names rather than native names of languages.
ISO 639-3: three-letter codes, the same as 639-2/T for languages, but with distinct
codes for each variety of an ISO 639 macrolanguage.
"""

langs = [
    {
        "names": ["Abkhazian"],
        "639-1": "ab",
        "639-2/T": "abk",
        "639-2/B": "abk",
        "639-3": ["abk"],
    },
    {
        "names": ["Afar"],
        "639-1": "aa",
        "639-2/T": "aar",
        "639-2/B": "aar",
        "639-3": ["aar"],
    },
    {
        "names": ["Afrikaans"],
        "639-1": "akas",
        "639-2/T": "afr",
        "639-2/B": "afr",
        "639-3": ["afr"],
    },
    {
        "names": ["Akan"],
        "639-1": "ak",
        "639-2/T": "aka",
        "639-2/B": "aka",
        "639-3": ["aka", "fat", "twi"],
    },
    {
        "names": ["Albanian"],
        "639-1": "sq",
        "639-2/T": "sqi",
        "639-2/B": "alb",
        "639-3": ["sqi", "aae", "aat", "aln", "als"],
    },
    {
        "names": ["Amharic"],
        "639-1": "am",
        "639-2/T": "amh",
        "639-2/B": "amh",
        "639-3": ["amh"],
    },
    {
        "names": ["Arabic"],
        "639-1": "ar",
        "639-2/T": "ara",
        "639-2/B": "ara",
        "639-3": [
            "ara",
            "aao",
            "abh",
            "abv",
            "acm",
            "acq",
            "acw",
            "acx",
            "acy",
            "adf",
            "aeb",
            "aec",
            "afb",
            "ajp",
            "apc",
            "apd",
            "arb",
            "arq",
            "ars",
            "ary",
            "arz",
            "auz",
            "avl",
            "ayh",
            "ayl",
            "ayn",
            "ayp",
            "pga",
            "shu",
            "ssh",
        ],
    },
    {
        "names": ["Aragonese"],
        "639-1": "an",
        "639-2/T": "arg",
        "639-2/B": "arg",
        "639-3": ["arg"],
    },
    {
        "names": ["Armenian"],
        "639-1": "hy",
        "639-2/T": "hye",
        "639-2/B": "arm",
        "639-3": ["hye"],
    },
    {
        "names": ["Assamese"],
        "639-1": "as",
        "639-2/T": "asm",
        "639-2/B": "asm",
        "639-3": ["asm"],
    },
    {
        "names": ["Avaric"],
        "639-1": "av",
        "639-2/T": "ava",
        "639-2/B": "ava",
        "639-3": ["ava"],
    },
    {
        "names": ["Avestan"],
        "639-1": "ae",
        "639-2/T": "ave",
        "639-2/B": "ave",
        "639-3": ["ave"],
    },
    {
        "names": ["Aymara"],
        "639-1": "ay",
        "639-2/T": "aym",
        "639-2/B": "aym",
        "639-3": ["aym", "ayr", "ayc"],
    },
    {
        "names": ["Azerbaijani"],
        "639-1": "az",
        "639-2/T": "aze",
        "639-2/B": "aze",
        "639-3": ["aze", "azj", "azb"],
    },
    {
        "names": ["Bambara"],
        "639-1": "bm",
        "639-2/T": "bam",
        "639-2/B": "bam",
        "639-3": ["bam"],
    },
    {
        "names": ["Bashkir"],
        "639-1": "ba",
        "639-2/T": "bak",
        "639-2/B": "bak",
        "639-3": ["bak"],
    },
    {
        "names": ["Basque"],
        "639-1": "eu",
        "639-2/T": "eus",
        "639-2/B": "baq",
        "639-3": ["eus"],
    },
    {
        "names": ["Belarusian"],
        "639-1": "be",
        "639-2/T": "bel",
        "639-2/B": "bel",
        "639-3": ["bel"],
    },
    {
        "names": ["Bengali"],
        "639-1": "bn",
        "639-2/T": "ben",
        "639-2/B": "ben",
        "639-3": ["ben"],
    },
    {
        "names": ["Bislama"],
        "639-1": "bi",
        "639-2/T": "bis",
        "639-2/B": "bis",
        "639-3": ["bis"],
    },
    {
        "names": ["Bosnian"],
        "639-1": "bs",
        "639-2/T": "bos",
        "639-2/B": "bos",
        "639-3": ["bos"],
    },
    {
        "names": ["Breton"],
        "639-1": "br",
        "639-2/T": "bre",
        "639-2/B": "bre",
        "639-3": ["bre"],
    },
    {
        "names": ["Bulgarian"],
        "639-1": "bg",
        "639-2/T": "bul",
        "639-2/B": "bul",
        "639-3": ["bul"],
    },
    {
        "names": ["Burmese"],
        "639-1": "my",
        "639-2/T": "mya",
        "639-2/B": "bur",
        "639-3": ["mya"],
    },
    {
        "names": ["Catalan", "Valencian"],
        "639-1": "ca",
        "639-2/T": "cat",
        "639-2/B": "cat",
        "639-3": ["cat"],
    },
    {
        "names": ["Chamorro"],
        "639-1": "ch",
        "639-2/T": "cha",
        "639-2/B": "cha",
        "639-3": ["cha"],
    },
    {
        "names": ["Chechen"],
        "639-1": "ce",
        "639-2/T": "che",
        "639-2/B": "che",
        "639-3": ["che"],
    },
    {
        "names": ["Chichewa", "Chewa", "Nyanja"],
        "639-1": "ny",
        "639-2/T": "nya",
        "639-2/B": "nya",
        "639-3": ["nya"],
    },
    {
        "names": ["Chinese"],
        "639-1": "zh",
        "639-2/T": "zho",
        "639-2/B": "chi",
        "639-3": [
            "zho",
            "cdo",
            "cjy",
            "cmn",
            "cnp",
            "cpx",
            "csp",
            "czh",
            "czo",
            "gan",
            "hak",
            "hsn",
            "lzh",
            "mnp",
            "nan",
            "wuu",
            "yue",
        ],
    },
    {
        "names": [
            "Church Slavic",
            "Old Slavonic",
            "Church Slavonic",
            "Old Bulgarian",
            "Old Church Slavonic",
        ],
        "639-1": "cu",
        "639-2/T": "chu",
        "639-2/B": "chu",
        "639-3": ["chu"],
    },
    {
        "names": ["Chuvash"],
        "639-1": "cv",
        "639-2/T": "chv",
        "639-2/B": "chv",
        "639-3": ["chv"],
    },
    {
        "names": ["Cornish"],
        "639-1": "kw",
        "639-2/T": "cor",
        "639-2/B": "cor",
        "639-3": ["cor"],
    },
    {
        "names": ["Corsican"],
        "639-1": "co",
        "639-2/T": "cos",
        "639-2/B": "cos",
        "639-3": ["cos"],
    },
    {
        "names": ["Cree"],
        "639-1": "cr",
        "639-2/T": "cre",
        "639-2/B": "cre",
        "639-3": ["cre", "crm", "crl", "crk", "crj", "csw", "cwd"],
    },
    {
        "names": ["Croatian"],
        "639-1": "hr",
        "639-2/T": "hrv",
        "639-2/B": "hrv",
        "639-3": ["hrv"],
    },
    {
        "names": ["Czech"],
        "639-1": "cs",
        "639-2/T": "ces",
        "639-2/B": "cze",
        "639-3": ["ces"],
    },
    {
        "names": ["Danish"],
        "639-1": "da",
        "639-2/T": "dan",
        "639-2/B": "dan",
        "639-3": ["dan"],
    },
    {
        "names": ["Divehi", "Dhivehi", "Maldivian"],
        "639-1": "dv",
        "639-2/T": "div",
        "639-2/B": "div",
        "639-3": ["div"],
    },
    {
        "names": ["Dutch", "Flemish"],
        "639-1": "nl",
        "639-2/T": "nld",
        "639-2/B": "dut",
        "639-3": ["nld"],
    },
    {
        "names": ["Dzongkha"],
        "639-1": "dz",
        "639-2/T": "dzo",
        "639-2/B": "dzo",
        "639-3": ["dzo"],
    },
    {
        "names": ["English"],
        "639-1": "en",
        "639-2/T": "eng",
        "639-2/B": "eng",
        "639-3": ["eng"],
    },
    {
        "names": ["Esperanto"],
        "639-1": "eo",
        "639-2/T": "epo",
        "639-2/B": "epo",
        "639-3": ["epo"],
    },
    {
        "names": ["Estonian"],
        "639-1": "et",
        "639-2/T": "est",
        "639-2/B": "est",
        "639-3": ["est", "ekk", "vro"],
    },
    {
        "names": ["Ewe"],
        "639-1": "ee",
        "639-2/T": "ewe",
        "639-2/B": "ewe",
        "639-3": ["ewe"],
    },
    {
        "names": ["Faroese"],
        "639-1": "fo",
        "639-2/T": "fao",
        "639-2/B": "fao",
        "639-3": ["fao"],
    },
    {
        "names": ["Fijian"],
        "639-1": "fj",
        "639-2/T": "fij",
        "639-2/B": "fij",
        "639-3": ["fij"],
    },
    {
        "names": ["Finnish"],
        "639-1": "fi",
        "639-2/T": "fin",
        "639-2/B": "fin",
        "639-3": ["fin"],
    },
    {
        "names": ["French"],
        "639-1": "fr",
        "639-2/T": "fra",
        "639-2/B": "fre",
        "639-3": ["fra"],
    },
    {
        "names": ["Western Frisian"],
        "639-1": "fy",
        "639-2/T": "fry",
        "639-2/B": "fry",
        "639-3": ["fry"],
    },
    {
        "names": ["Fulah"],
        "639-1": "ff",
        "639-2/T": "ful",
        "639-2/B": "ful",
        "639-3": ["ful", "fub", "fui", "fue", "fuq", "ffm", "fuv", "fuc", "fuf", "fuh"],
    },
    {
        "names": ["Gaelic", "Scottish Gaelic"],
        "639-1": "gd",
        "639-2/T": "gla",
        "639-2/B": "gla",
        "639-3": ["gla"],
    },
    {
        "names": ["Galician"],
        "639-1": "gl",
        "639-2/T": "glg",
        "639-2/B": "glg",
        "639-3": ["glg"],
    },
    {
        "names": ["Ganda"],
        "639-1": "lg",
        "639-2/T": "lug",
        "639-2/B": "lug",
        "639-3": ["lug"],
    },
    {
        "names": ["Georgian"],
        "639-1": "ka",
        "639-2/T": "kat",
        "639-2/B": "geo",
        "639-3": ["kat"],
    },
    {
        "names": ["German"],
        "639-1": "de",
        "639-2/T": "deu",
        "639-2/B": "ger",
        "639-3": ["deu"],
    },
    {
        "names": ["Greek", "Modern (1453–)"],
        "639-1": "el",
        "639-2/T": "ell",
        "639-2/B": "gre",
        "639-3": ["ell"],
    },
    {
        "names": ["Kalaallisut", "Greenlandic"],
        "639-1": "kl",
        "639-2/T": "kal",
        "639-2/B": "kal",
        "639-3": ["kal"],
    },
    {
        "names": ["Guarani"],
        "639-1": "gn",
        "639-2/T": "grn",
        "639-2/B": "grn",
        "639-3": ["grn", "nhd", "gui", "gun", "gug", "gnw"],
    },
    {
        "names": ["Gujarati"],
        "639-1": "gu",
        "639-2/T": "guj",
        "639-2/B": "guj",
        "639-3": ["guj"],
    },
    {
        "names": ["Haitian", "Haitian Creole"],
        "639-1": "ht",
        "639-2/T": "hat",
        "639-2/B": "hat",
        "639-3": ["hat"],
    },
    {
        "names": ["Hausa"],
        "639-1": "ha",
        "639-2/T": "hau",
        "639-2/B": "hau",
        "639-3": ["hau"],
    },
    {
        "names": ["Hebrew"],
        "639-1": "he",
        "639-2/T": "heb",
        "639-2/B": "heb",
        "639-3": ["heb"],
    },
    {
        "names": ["Herero"],
        "639-1": "hz",
        "639-2/T": "her",
        "639-2/B": "her",
        "639-3": ["her"],
    },
    {
        "names": ["Hindi"],
        "639-1": "hi",
        "639-2/T": "hin",
        "639-2/B": "hin",
        "639-3": ["hin"],
    },
    {
        "names": ["Hiri Motu"],
        "639-1": "ho",
        "639-2/T": "hmo",
        "639-2/B": "hmo",
        "639-3": ["hmo"],
    },
    {
        "names": ["Hungarian"],
        "639-1": "hu",
        "639-2/T": "hun",
        "639-2/B": "hun",
        "639-3": ["hun"],
    },
    {
        "names": ["Icelandic"],
        "639-1": "is",
        "639-2/T": "isl",
        "639-2/B": "ice",
        "639-3": ["isl"],
    },
    {
        "names": ["Ido"],
        "639-1": "io",
        "639-2/T": "ido",
        "639-2/B": "ido",
        "639-3": ["ido"],
    },
    {
        "names": ["Igbo"],
        "639-1": "ig",
        "639-2/T": "ibo",
        "639-2/B": "ibo",
        "639-3": ["ibo"],
    },
    {
        "names": ["Indonesian"],
        "639-1": "id",
        "639-2/T": "ind",
        "639-2/B": "ind",
        "639-3": ["ind"],
    },
    {
        "names": ["Interlingua (International Auxiliary Language Association)"],
        "639-1": "ia",
        "639-2/T": "ina",
        "639-2/B": "ina",
        "639-3": ["ina"],
    },
    {
        "names": ["Interlingue", "Occidental"],
        "639-1": "ie",
        "639-2/T": "ile",
        "639-2/B": "ile",
        "639-3": ["ile"],
    },
    {
        "names": ["Inuktitut"],
        "639-1": "iu",
        "639-2/T": "iku",
        "639-2/B": "iku",
        "639-3": ["iku", "ike", "ikt"],
    },
    {
        "names": ["Inupiaq"],
        "639-1": "ik",
        "639-2/T": "ipk",
        "639-2/B": "ipk",
        "639-3": ["ipk", "esi", "esk"],
    },
    {
        "names": ["Irish"],
        "639-1": "ga",
        "639-2/T": "gle",
        "639-2/B": "gle",
        "639-3": ["gle"],
    },
    {
        "names": ["Italian"],
        "639-1": "it",
        "639-2/T": "ita",
        "639-2/B": "ita",
        "639-3": ["ita"],
    },
    {
        "names": ["Japanese"],
        "639-1": "ja",
        "639-2/T": "jpn",
        "639-2/B": "jpn",
        "639-3": ["jpn"],
    },
    {
        "names": ["Javanese"],
        "639-1": "jv",
        "639-2/T": "jav",
        "639-2/B": "jav",
        "639-3": ["jav"],
    },
    {
        "names": ["Kannada"],
        "639-1": "kn",
        "639-2/T": "kan",
        "639-2/B": "kan",
        "639-3": ["kan"],
    },
    {
        "names": ["Kanuri"],
        "639-1": "kr",
        "639-2/T": "kau",
        "639-2/B": "kau",
        "639-3": ["kau", "knc", "kby", "krt"],
    },
    {
        "names": ["Kashmiri"],
        "639-1": "ks",
        "639-2/T": "kas",
        "639-2/B": "kas",
        "639-3": ["kas"],
    },
    {
        "names": ["Kazakh"],
        "639-1": "kk",
        "639-2/T": "kaz",
        "639-2/B": "kaz",
        "639-3": ["kaz"],
    },
    {
        "names": ["Central Khmer"],
        "639-1": "km",
        "639-2/T": "khm",
        "639-2/B": "khm",
        "639-3": ["khm"],
    },
    {
        "names": ["Kikuyu", "Gikuyu"],
        "639-1": "ki",
        "639-2/T": "kik",
        "639-2/B": "kik",
        "639-3": ["kik"],
    },
    {
        "names": ["Kinyarwanda"],
        "639-1": "rw",
        "639-2/T": "kin",
        "639-2/B": "kin",
        "639-3": ["kin"],
    },
    {
        "names": ["Kirghiz", "Kyrgyz"],
        "639-1": "ky",
        "639-2/T": "kir",
        "639-2/B": "kir",
        "639-3": ["kir"],
    },
    {
        "names": ["Komi"],
        "639-1": "kv",
        "639-2/T": "kom",
        "639-2/B": "kom",
        "639-3": ["kom", "koi", "kpv"],
    },
    {
        "names": ["Kongo"],
        "639-1": "kg",
        "639-2/T": "kon",
        "639-2/B": "kon",
        "639-3": ["kon", "kng", "ldi", "kwy"],
    },
    {
        "names": ["Korean"],
        "639-1": "ko",
        "639-2/T": "kor",
        "639-2/B": "kor",
        "639-3": ["kor"],
    },
    {
        "names": ["Kuanyama", "Kwanyama"],
        "639-1": "kj",
        "639-2/T": "kua",
        "639-2/B": "kua",
        "639-3": ["kua"],
    },
    {
        "names": ["Kurdish"],
        "639-1": "ku",
        "639-2/T": "kur",
        "639-2/B": "kur",
        "639-3": ["kur", "ckb", "kmr", "sdh"],
    },
    {
        "names": ["Lao"],
        "639-1": "lo",
        "639-2/T": "lao",
        "639-2/B": "lao",
        "639-3": ["lao"],
    },
    {
        "names": ["Latin"],
        "639-1": "la",
        "639-2/T": "lat",
        "639-2/B": "lat",
        "639-3": ["lat"],
    },
    {
        "names": ["Latvian"],
        "639-1": "lv",
        "639-2/T": "lav",
        "639-2/B": "lav",
        "639-3": ["lav", "ltg", "lvs"],
    },
    {
        "names": ["Limburgan", "Limburger", "Limburgish"],
        "639-1": "li",
        "639-2/T": "lim",
        "639-2/B": "lim",
        "639-3": ["lim"],
    },
    {
        "names": ["Lingala"],
        "639-1": "ln",
        "639-2/T": "lin",
        "639-2/B": "lin",
        "639-3": ["lin"],
    },
    {
        "names": ["Lithuanian"],
        "639-1": "lt",
        "639-2/T": "lit",
        "639-2/B": "lit",
        "639-3": ["lit"],
    },
    {
        "names": ["Luba-Katanga"],
        "639-1": "lu",
        "639-2/T": "lub",
        "639-2/B": "lub",
        "639-3": ["lub"],
    },
    {
        "names": ["Luxembourgish", "Letzeburgesch"],
        "639-1": "lb",
        "639-2/T": "ltz",
        "639-2/B": "ltz",
        "639-3": ["ltz"],
    },
    {
        "names": ["Macedonian"],
        "639-1": "mk",
        "639-2/T": "mkd",
        "639-2/B": "mac",
        "639-3": ["mkd"],
    },
    {
        "names": ["Malagasy"],
        "639-1": "mg",
        "639-2/T": "mlg",
        "639-2/B": "mlg",
        "639-3": [
            "mlg",
            "xmv",
            "bhr",
            "msh",
            "bmm",
            "plt",
            "skg",
            "bzc",
            "tkg",
            "tdx",
            "txy",
            "xmw",
        ],
    },
    {
        "names": ["Malay"],
        "639-1": "ms",
        "639-2/T": "msa",
        "639-2/B": "may",
        "639-3": [
            "msa",
            "btj",
            "mfb",
            "bjn",
            "bve",
            "kxd",
            "bvu",
            "pse",
            "coa",
            "liw",
            "dup",
            "hji",
            "ind",
            "jak",
            "jax",
            "vkk",
            "meo",
            "kvr",
            "mqg",
            "kvb",
            "lce",
            "lcf",
            "zlm",
            "xmm",
            "min",
            "mui",
            "zmi",
            "max",
            "orn",
            "ors",
            "mfa",
            "pel",
            "msi",
            "zsm",
            "tmw",
            "vkt",
            "urk",
        ],
    },
    {
        "names": ["Malayalam"],
        "639-1": "ml",
        "639-2/T": "mal",
        "639-2/B": "mal",
        "639-3": ["mal"],
    },
    {
        "names": ["Maltese"],
        "639-1": "mt",
        "639-2/T": "mlt",
        "639-2/B": "mlt",
        "639-3": ["mlt"],
    },
    {
        "names": ["Manx"],
        "639-1": "gv",
        "639-2/T": "glv",
        "639-2/B": "glv",
        "639-3": ["glv"],
    },
    {
        "names": ["Maori"],
        "639-1": "mi",
        "639-2/T": "mri",
        "639-2/B": "mao",
        "639-3": ["mri"],
    },
    {
        "names": ["Marathi"],
        "639-1": "mr",
        "639-2/T": "mar",
        "639-2/B": "mar",
        "639-3": ["mar"],
    },
    {
        "names": ["Marshallese"],
        "639-1": "mh",
        "639-2/T": "mah",
        "639-2/B": "mah",
        "639-3": ["mah"],
    },
    {
        "names": ["Mongolian"],
        "639-1": "mn",
        "639-2/T": "mon",
        "639-2/B": "mon",
        "639-3": ["mon", "khk", "mvf"],
    },
    {
        "names": ["Nauru"],
        "639-1": "na",
        "639-2/T": "nau",
        "639-2/B": "nau",
        "639-3": ["nau"],
    },
    {
        "names": ["Navajo", "Navaho"],
        "639-1": "nv",
        "639-2/T": "nav",
        "639-2/B": "nav",
        "639-3": ["nav"],
    },
    {
        "names": ["North Ndebele"],
        "639-1": "nd",
        "639-2/T": "nde",
        "639-2/B": "nde",
        "639-3": ["nde"],
    },
    {
        "names": ["South Ndebele"],
        "639-1": "nr",
        "639-2/T": "nbl",
        "639-2/B": "nbl",
        "639-3": ["nbl"],
    },
    {
        "names": ["Ndonga"],
        "639-1": "ng",
        "639-2/T": "ndo",
        "639-2/B": "ndo",
        "639-3": ["ndo"],
    },
    {
        "names": ["Nepali"],
        "639-1": "ne",
        "639-2/T": "nep",
        "639-2/B": "nep",
        "639-3": ["nep", "dty", "npi"],
    },
    {
        "names": ["Norwegian"],
        "639-1": "no",
        "639-2/T": "nor",
        "639-2/B": "nor",
        "639-3": ["nor", "nob", "nno"],
    },
    {
        "names": ["Sichuan Yi", "Nuosu"],
        "639-1": "ii",
        "639-2/T": "iii",
        "639-2/B": "iii",
        "639-3": ["iii"],
    },
    {
        "names": ["Occitan"],
        "639-1": "oc",
        "639-2/T": "oci",
        "639-2/B": "oci",
        "639-3": ["oci"],
    },
    {
        "names": ["Ojibwa"],
        "639-1": "oj",
        "639-2/T": "oji",
        "639-2/B": "oji",
        "639-3": ["oji", "ciw", "ojb", "ojc", "ojg", "ojs", "ojw", "otw"],
    },
    {
        "names": ["Oriya"],
        "639-1": "or",
        "639-2/T": "ori",
        "639-2/B": "ori",
        "639-3": ["ori", "ory", "spv"],
    },
    {
        "names": ["Oromo"],
        "639-1": "om",
        "639-2/T": "orm",
        "639-2/B": "orm",
        "639-3": ["orm", "gax", "hae", "orc", "gaz"],
    },
    {
        "names": ["Ossetian", "Ossetic"],
        "639-1": "os",
        "639-2/T": "oss",
        "639-2/B": "oss",
        "639-3": ["oss"],
    },
    {
        "names": ["Pali"],
        "639-1": "pi",
        "639-2/T": "pli",
        "639-2/B": "pli",
        "639-3": ["pli"],
    },
    {
        "names": ["Pashto", "Pushto"],
        "639-1": "ps",
        "639-2/T": "pus",
        "639-2/B": "pus",
        "639-3": ["pus", "pst", "pbu", "pbt"],
    },
    {
        "names": ["Persian"],
        "639-1": "fa",
        "639-2/T": "fas",
        "639-2/B": "per",
        "639-3": ["fas", "prs", "pes"],
    },
    {
        "names": ["Polish"],
        "639-1": "pl",
        "639-2/T": "pol",
        "639-2/B": "pol",
        "639-3": ["pol"],
    },
    {
        "names": ["Portuguese"],
        "639-1": "pt",
        "639-2/T": "por",
        "639-2/B": "por",
        "639-3": ["por"],
    },
    {
        "names": ["Punjabi", "Panjabi"],
        "639-1": "pa",
        "639-2/T": "pan",
        "639-2/B": "pan",
        "639-3": ["pan"],
    },
    {
        "names": ["Quechua"],
        "639-1": "qu",
        "639-2/T": "que",
        "639-2/B": "que",
        "639-3": [
            "que",
            "qva",
            "qxu",
            "quy",
            "qvc",
            "qvl",
            "qud",
            "qxr",
            "quk",
            "qug",
            "qxc",
            "qxa",
            "qwc",
            "qwa",
            "quz",
            "qve",
            "qub",
            "qvh",
            "qwh",
            "qvw",
            "qvi",
            "qxw",
            "quf",
            "qvj",
            "qvm",
            "qvo",
            "qul",
            "qvn",
            "qxn",
            "qvz",
            "qvp",
            "qxh",
            "qxp",
            "qxl",
            "qvs",
            "qxt",
            "qus",
            "qws",
            "quh",
            "qxo",
            "qup",
            "quw",
            "qur",
            "qux",
        ],
    },
    {
        "names": ["Romanian", "Moldavian", "Moldovan"],
        "639-1": "ro",
        "639-2/T": "ron",
        "639-2/B": "rum",
        "639-3": ["ron"],
    },
    {
        "names": ["Romansh"],
        "639-1": "rm",
        "639-2/T": "roh",
        "639-2/B": "roh",
        "639-3": ["roh"],
    },
    {
        "names": ["Rundi"],
        "639-1": "rn",
        "639-2/T": "run",
        "639-2/B": "run",
        "639-3": ["run"],
    },
    {
        "names": ["Russian"],
        "639-1": "ru",
        "639-2/T": "rus",
        "639-2/B": "rus",
        "639-3": ["rus"],
    },
    {
        "names": ["Northern Sami"],
        "639-1": "se",
        "639-2/T": "sme",
        "639-2/B": "sme",
        "639-3": ["sme"],
    },
    {
        "names": ["Samoan"],
        "639-1": "sm",
        "639-2/T": "smo",
        "639-2/B": "smo",
        "639-3": ["smo"],
    },
    {
        "names": ["Sango"],
        "639-1": "sg",
        "639-2/T": "sag",
        "639-2/B": "sag",
        "639-3": ["sag"],
    },
    {
        "names": ["Sanskrit"],
        "639-1": "sa",
        "639-2/T": "san",
        "639-2/B": "san",
        "639-3": ["san"],
    },
    {
        "names": ["Sardinian"],
        "639-1": "sc",
        "639-2/T": "srd",
        "639-2/B": "srd",
        "639-3": ["srd", "sro", "sdn", "src", "sdc"],
    },
    {
        "names": ["Serbian"],
        "639-1": "sr",
        "639-2/T": "srp",
        "639-2/B": "srp",
        "639-3": ["srp"],
    },
    {
        "names": ["Shona"],
        "639-1": "sn",
        "639-2/T": "sna",
        "639-2/B": "sna",
        "639-3": ["sna"],
    },
    {
        "names": ["Sindhi"],
        "639-1": "sd",
        "639-2/T": "snd",
        "639-2/B": "snd",
        "639-3": ["snd"],
    },
    {
        "names": ["Sinhala", "Sinhalese"],
        "639-1": "si",
        "639-2/T": "sin",
        "639-2/B": "sin",
        "639-3": ["sin"],
    },
    {
        "names": ["Slovak"],
        "639-1": "sk",
        "639-2/T": "slk",
        "639-2/B": "slo",
        "639-3": ["slk"],
    },
    {
        "names": ["Slovenian"],
        "639-1": "sl",
        "639-2/T": "slv",
        "639-2/B": "slv",
        "639-3": ["slv"],
    },
    {
        "names": ["Somali"],
        "639-1": "so",
        "639-2/T": "som",
        "639-2/B": "som",
        "639-3": ["som"],
    },
    {
        "names": ["Southern Sotho"],
        "639-1": "st",
        "639-2/T": "sot",
        "639-2/B": "sot",
        "639-3": ["sot"],
    },
    {
        "names": ["Spanish", "Castilian"],
        "639-1": "es",
        "639-2/T": "spa",
        "639-2/B": "spa",
        "639-3": ["spa"],
    },
    {
        "names": ["Sundanese"],
        "639-1": "su",
        "639-2/T": "sun",
        "639-2/B": "sun",
        "639-3": ["sun"],
    },
    {
        "names": ["Swahili"],
        "639-1": "sw",
        "639-2/T": "swa",
        "639-2/B": "swa",
        "639-3": ["swa", "swc", "swh"],
    },
    {
        "names": ["Swati"],
        "639-1": "ss",
        "639-2/T": "ssw",
        "639-2/B": "ssw",
        "639-3": ["ssw"],
    },
    {
        "names": ["Swedish"],
        "639-1": "sv",
        "639-2/T": "swe",
        "639-2/B": "swe",
        "639-3": ["swe"],
    },
    {
        "names": ["Tagalog"],
        "639-1": "tl",
        "639-2/T": "tgl",
        "639-2/B": "tgl",
        "639-3": ["tgl"],
    },
    {
        "names": ["Tahitian"],
        "639-1": "ty",
        "639-2/T": "tah",
        "639-2/B": "tah",
        "639-3": ["tah"],
    },
    {
        "names": ["Tajik"],
        "639-1": "tg",
        "639-2/T": "tgk",
        "639-2/B": "tgk",
        "639-3": ["tgk"],
    },
    {
        "names": ["Tamil"],
        "639-1": "ta",
        "639-2/T": "tam",
        "639-2/B": "tam",
        "639-3": ["tam"],
    },
    {
        "names": ["Tatar"],
        "639-1": "tt",
        "639-2/T": "tat",
        "639-2/B": "tat",
        "639-3": ["tat"],
    },
    {
        "names": ["Telugu"],
        "639-1": "te",
        "639-2/T": "tel",
        "639-2/B": "tel",
        "639-3": ["tel"],
    },
    {
        "names": ["Thai"],
        "639-1": "th",
        "639-2/T": "tha",
        "639-2/B": "tha",
        "639-3": ["tha"],
    },
    {
        "names": ["Tibetan"],
        "639-1": "bo",
        "639-2/T": "bod",
        "639-2/B": "tib",
        "639-3": ["bod"],
    },
    {
        "names": ["Tigrinya"],
        "639-1": "ti",
        "639-2/T": "tir",
        "639-2/B": "tir",
        "639-3": ["tir"],
    },
    {
        "names": ["Tonga (Tonga Islands)"],
        "639-1": "to",
        "639-2/T": "ton",
        "639-2/B": "ton",
        "639-3": ["ton"],
    },
    {
        "names": ["Tsonga"],
        "639-1": "ts",
        "639-2/T": "tso",
        "639-2/B": "tso",
        "639-3": ["tso"],
    },
    {
        "names": ["Tswana"],
        "639-1": "tn",
        "639-2/T": "tsn",
        "639-2/B": "tsn",
        "639-3": ["tsn"],
    },
    {
        "names": ["Turkish"],
        "639-1": "tr",
        "639-2/T": "tur",
        "639-2/B": "tur",
        "639-3": ["tur"],
    },
    {
        "names": ["Turkmen"],
        "639-1": "tk",
        "639-2/T": "tuk",
        "639-2/B": "tuk",
        "639-3": ["tuk"],
    },
    {
        "names": ["Twi"],
        "639-1": "tw",
        "639-2/T": "twi",
        "639-2/B": "twi",
        "639-3": ["twi"],
    },
    {
        "names": ["Uighur", "Uyghur"],
        "639-1": "ug",
        "639-2/T": "uig",
        "639-2/B": "uig",
        "639-3": ["uig"],
    },
    {
        "names": ["Ukrainian"],
        "639-1": "uk",
        "639-2/T": "ukr",
        "639-2/B": "ukr",
        "639-3": ["ukr"],
    },
    {
        "names": ["Urdu"],
        "639-1": "ur",
        "639-2/T": "urd",
        "639-2/B": "urd",
        "639-3": ["urd"],
    },
    {
        "names": ["Uzbek"],
        "639-1": "uz",
        "639-2/T": "uzb",
        "639-2/B": "uzb",
        "639-3": ["uzb", "uzn", "uzs"],
    },
    {
        "names": ["Venda"],
        "639-1": "ve",
        "639-2/T": "ven",
        "639-2/B": "ven",
        "639-3": ["ven"],
    },
    {
        "names": ["Vietnamese"],
        "639-1": "vi",
        "639-2/T": "vie",
        "639-2/B": "vie",
        "639-3": ["vie"],
    },
    {
        "names": ["Volapük"],
        "639-1": "vo",
        "639-2/T": "vol",
        "639-2/B": "vol",
        "639-3": ["vol"],
    },
    {
        "names": ["Walloon"],
        "639-1": "wa",
        "639-2/T": "wln",
        "639-2/B": "wln",
        "639-3": ["wln"],
    },
    {
        "names": ["Welsh"],
        "639-1": "cy",
        "639-2/T": "cym",
        "639-2/B": "wel",
        "639-3": ["cym"],
    },
    {
        "names": ["Wolof"],
        "639-1": "wo",
        "639-2/T": "wol",
        "639-2/B": "wol",
        "639-3": ["wol"],
    },
    {
        "names": ["Xhosa"],
        "639-1": "xh",
        "639-2/T": "xho",
        "639-2/B": "xho",
        "639-3": ["xho"],
    },
    {
        "names": ["Yiddish"],
        "639-1": "yi",
        "639-2/T": "yid",
        "639-2/B": "yid",
        "639-3": ["yid", "ydd", "yih"],
    },
    {
        "names": ["Yoruba"],
        "639-1": "yo",
        "639-2/T": "yor",
        "639-2/B": "yor",
        "639-3": ["yor"],
    },
    {
        "names": ["Zhuang", "Chuang"],
        "639-1": "za",
        "639-2/T": "zha",
        "639-2/B": "zha",
        "639-3": [
            "zha",
            "zch",
            "zhd",
            "zeh",
            "zgb",
            "zgn",
            "zln",
            "zlj",
            "zlq",
            "zgm",
            "zhn",
            "zqe",
            "zyg",
            "zyb",
            "zyn",
            "zyj",
            "zzj",
        ],
    },
    {
        "names": ["Zulu"],
        "639-1": "zu",
        "639-2/T": "zul",
        "639-2/B": "zul",
        "639-3": ["zul"],
    },
]
