import datetime

import pytest
from bs4 import BeautifulSoup

from clinical_mdr_api.models import (
    Activity,
    CTTermName,
    StudySelectionActivity,
    StudyVisit,
)
from clinical_mdr_api.models.activities.activity import ActivityHierarchySimpleModel
from clinical_mdr_api.models.table_with_headers import TableHeader, TableWithHeaders
from clinical_mdr_api.models.utils import GenericFilteringReturn
from clinical_mdr_api.services.study_flowchart import StudyFlowchartService

USER_INITIALS = "unknown-user"

STUDY_VISITS = GenericFilteringReturn.create(
    items=[
        StudyVisit(
            study_epoch_uid="StudyEpoch_000001",
            visit_type_uid="CTTerm_000171",
            time_reference_uid="CTTerm_000117",
            time_value=-2,
            time_unit_uid="UnitDefinition_000171",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000021",
            study_uid="Study_000001",
            study_epoch_name="Screening",
            epoch_uid="C48262_SCREENING",
            order=1,
            visit_type_name="Screening",
            time_reference_name="Global Anchor Visit",
            time_unit_name="weeks",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=-1209600.0,
            duration_time_unit="UnitDefinition_000171",
            study_day_number=-14,
            study_duration_days_label="-15 days",
            study_day_label="Day -14",
            study_week_number=-2,
            study_duration_weeks_label="-3 weeks",
            study_week_label="Week -2",
            visit_number=1,
            visit_subnumber=0,
            unique_visit_number=100,
            visit_subname="Visit 1",
            visit_sublabel=None,
            visit_name="Visit 1",
            visit_short_name="V1",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:48",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=0,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=True,
            uid="StudyVisit_000022",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=2,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=0.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=1,
            study_duration_days_label="0 days",
            study_day_label="Day 1",
            study_week_number=1,
            study_duration_weeks_label="0 weeks",
            study_week_label="Week 1",
            visit_number=2,
            visit_subnumber=0,
            unique_visit_number=200,
            visit_subname="Visit 2",
            visit_sublabel=None,
            visit_name="Visit 2",
            visit_short_name="V2",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:49",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=7,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000023",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=3,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=604800.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=8,
            study_duration_days_label="7 days",
            study_day_label="Day 8",
            study_week_number=2,
            study_duration_weeks_label="1 weeks",
            study_week_label="Week 2",
            visit_number=3,
            visit_subnumber=0,
            unique_visit_number=300,
            visit_subname="Visit 3",
            visit_sublabel=None,
            visit_name="Visit 3",
            visit_short_name="V3",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:49",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=14,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000024",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=4,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=1209600.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=15,
            study_duration_days_label="14 days",
            study_day_label="Day 15",
            study_week_number=3,
            study_duration_weeks_label="2 weeks",
            study_week_label="Week 3",
            visit_number=4,
            visit_subnumber=0,
            unique_visit_number=400,
            visit_subname="Visit 4",
            visit_sublabel=None,
            visit_name="Visit 4",
            visit_short_name="V4",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:49",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=21,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000025",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=5,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=1814400.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=22,
            study_duration_days_label="21 days",
            study_day_label="Day 22",
            study_week_number=4,
            study_duration_weeks_label="3 weeks",
            study_week_label="Week 4",
            visit_number=5,
            visit_subnumber=0,
            unique_visit_number=500,
            visit_subname="Visit 5",
            visit_sublabel=None,
            visit_name="Visit 5",
            visit_short_name="V5",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:50",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=28,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000026",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=6,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=2419200.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=29,
            study_duration_days_label="28 days",
            study_day_label="Day 29",
            study_week_number=5,
            study_duration_weeks_label="4 weeks",
            study_week_label="Week 5",
            visit_number=6,
            visit_subnumber=0,
            unique_visit_number=600,
            visit_subname="Visit 6",
            visit_sublabel=None,
            visit_name="Visit 6",
            visit_short_name="V6",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:50",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=35,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000027",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=7,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=3024000.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=36,
            study_duration_days_label="35 days",
            study_day_label="Day 36",
            study_week_number=6,
            study_duration_weeks_label="5 weeks",
            study_week_label="Week 6",
            visit_number=7,
            visit_subnumber=0,
            unique_visit_number=700,
            visit_subname="Visit 7",
            visit_sublabel=None,
            visit_name="Visit 7",
            visit_short_name="V7",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:50",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=42,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000028",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=8,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=3628800.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=43,
            study_duration_days_label="42 days",
            study_day_label="Day 43",
            study_week_number=7,
            study_duration_weeks_label="6 weeks",
            study_week_label="Week 7",
            visit_number=8,
            visit_subnumber=0,
            unique_visit_number=800,
            visit_subname="Visit 8",
            visit_sublabel=None,
            visit_name="Visit 8",
            visit_short_name="V8",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:50",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=49,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group="TreatGroup",
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000029",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=9,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=4233600.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=50,
            study_duration_days_label="49 days",
            study_day_label="Day 50",
            study_week_number=8,
            study_duration_weeks_label="7 weeks",
            study_week_label="Week 8",
            visit_number=9,
            visit_subnumber=0,
            unique_visit_number=900,
            visit_subname="Visit 9",
            visit_sublabel=None,
            visit_name="Visit 9",
            visit_short_name="V9",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:50",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000117",
            time_value=56,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group="TreatGroup",
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000030",
            study_uid="Study_000001",
            study_epoch_name="Treatment",
            epoch_uid="C101526_TREATMENT",
            order=10,
            visit_type_name="Treatment",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=4838400.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=57,
            study_duration_days_label="56 days",
            study_day_label="Day 57",
            study_week_number=9,
            study_duration_weeks_label="8 weeks",
            study_week_label="Week 9",
            visit_number=10,
            visit_subnumber=0,
            unique_visit_number=1000,
            visit_subname="Visit 10",
            visit_sublabel=None,
            visit_name="Visit 10",
            visit_short_name="V10",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-24 11:52:51",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000042",
            visit_type_uid="CTTerm_000176",
            time_reference_uid="CTTerm_000113",
            time_value=1,
            time_unit_uid="UnitDefinition_000166",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000044",
            study_uid="Study_000001",
            study_epoch_name="Extension",
            epoch_uid="CTTerm_000007",
            order=11,
            visit_type_name="Treatment",
            time_reference_name="Previous Visit",
            time_unit_name="week",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=5443200.0,
            duration_time_unit="UnitDefinition_000166",
            study_day_number=64,
            study_duration_days_label="7 days",
            study_day_label="Day 64",
            study_week_number=10,
            study_duration_weeks_label="1 weeks",
            study_week_label="Week 10",
            visit_number=11,
            visit_subnumber=0,
            unique_visit_number=1100,
            visit_subname="Visit 11",
            visit_sublabel=None,
            visit_name="Visit 11",
            visit_short_name="V11",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-26 02:14:58",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000003",
            visit_type_uid="CTTerm_000161",
            time_reference_uid="CTTerm_000117",
            time_value=182,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000080",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000031",
            study_uid="Study_000001",
            study_epoch_name="Follow-up",
            epoch_uid="C99158_FOLLOW-UP",
            order=12,
            visit_type_name="Follow-up",
            time_reference_name="Global Anchor Visit",
            time_unit_name="days",
            visit_contact_mode_name="On Site Visit",
            epoch_allocation_name=None,
            duration_time=15724800.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=183,
            study_duration_days_label="182 days",
            study_day_label="Day 183",
            study_week_number=27,
            study_duration_weeks_label="26 weeks",
            study_week_label="Week 27",
            visit_number=12,
            visit_subnumber=0,
            unique_visit_number=1200,
            visit_subname="Visit 12",
            visit_sublabel=None,
            visit_name="Visit 12",
            visit_short_name="V12",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-08-26 02:14:31",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000034",
            visit_type_uid="CTTerm_000164",
            time_reference_uid="CTTerm_000113",
            time_value=183,
            time_unit_uid="UnitDefinition_000151",
            visit_sublabel_codelist_uid=None,
            visit_sublabel_reference=None,
            legacy_visit_id=None,
            legacy_visit_type_alias=None,
            legacy_name=None,
            legacy_subname=None,
            consecutive_visit_group=None,
            show_visit=True,
            min_visit_window_value=0,
            max_visit_window_value=0,
            visit_window_unit_uid="UnitDefinition_000151",
            description=None,
            start_rule=None,
            end_rule=None,
            note=None,
            visit_contact_mode_uid="CTTerm_000079",
            epoch_allocation_uid=None,
            visit_class="SINGLE_VISIT",
            visit_subclass="SINGLE_VISIT",
            is_global_anchor_visit=False,
            uid="StudyVisit_000045",
            study_uid="Study_000001",
            study_epoch_name="Elimination",
            epoch_uid="CTTerm_000008",
            order=13,
            visit_type_name="Post treatment activity",
            time_reference_name="Previous Visit",
            time_unit_name="days",
            visit_contact_mode_name="Phone Contact",
            epoch_allocation_name=None,
            duration_time=31536000.0,
            duration_time_unit="UnitDefinition_000151",
            study_day_number=366,
            study_duration_days_label="183 days",
            study_day_label="Day 366",
            study_week_number=53,
            study_duration_weeks_label="26 weeks",
            study_week_label="Week 53",
            visit_number=13,
            visit_subnumber=0,
            unique_visit_number=1300,
            visit_subname="Visit 13",
            visit_sublabel=None,
            visit_name="Visit 13",
            visit_short_name="P13",
            visit_window_unit_name="days",
            status="DRAFT",
            start_date="2022-09-01 09:39:57",
            user_initials="unknown-user",
            possible_actions=["edit", "delete", "lock"],
            study_activity_count=0,
        ),
    ],
    total_count=0,
)

EPOCH_TERMS = {
    "C48262_SCREENING": CTTermName(
        term_uid="C48262_SCREENING",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Screening",
        sponsor_preferred_name_sentence_case="screening",
        order=1,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 1, 487948),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C98779_RUN-IN": CTTermName(
        term_uid="C98779_RUN-IN",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Run-in",
        sponsor_preferred_name_sentence_case="run-in",
        order=2,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 2, 35843),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C101526_TREATMENT": CTTermName(
        term_uid="C101526_TREATMENT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Treatment",
        sponsor_preferred_name_sentence_case="treatment",
        order=4,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 2, 582342),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C165873_OBSERVATION": CTTermName(
        term_uid="C165873_OBSERVATION",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Observation",
        sponsor_preferred_name_sentence_case="observation",
        order=5,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 3, 224234),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C123453_INDUCTION TREATMENT": CTTermName(
        term_uid="C123453_INDUCTION TREATMENT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Induction Therapy",
        sponsor_preferred_name_sentence_case="induction therapy",
        order=6,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 3, 857591),
        end_date=None,
        status="Final",
        version="2.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C102256_OPEN LABEL TREATMENT": CTTermName(
        term_uid="C102256_OPEN LABEL TREATMENT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Open Label Treatment",
        sponsor_preferred_name_sentence_case="open label treatment",
        order=7,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 4, 455043),
        end_date=None,
        status="Final",
        version="2.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C102255_BLINDED TREATMENT": CTTermName(
        term_uid="C102255_BLINDED TREATMENT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Blinded Treatment",
        sponsor_preferred_name_sentence_case="blinded treatment",
        order=8,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 5, 74978),
        end_date=None,
        status="Final",
        version="2.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C123452_CONTINUATION TREATMENT": CTTermName(
        term_uid="C123452_CONTINUATION TREATMENT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Continuation Treatment",
        sponsor_preferred_name_sentence_case="continuation treatment",
        order=9,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 5, 620200),
        end_date=None,
        status="Final",
        version="2.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C42872_WASHOUT": CTTermName(
        term_uid="C42872_WASHOUT",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Wash-out",
        sponsor_preferred_name_sentence_case="wash-out",
        order=10,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 6, 129830),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C99158_FOLLOW-UP": CTTermName(
        term_uid="C99158_FOLLOW-UP",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Follow-up",
        sponsor_preferred_name_sentence_case="follow-up",
        order=11,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 6, 690361),
        end_date=None,
        status="Final",
        version="3.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C16032_LONG-TERM FOLLOW-UP": CTTermName(
        term_uid="C16032_LONG-TERM FOLLOW-UP",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Long-term Follow-up",
        sponsor_preferred_name_sentence_case="long-term follow-up",
        order=12,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 7, 319109),
        end_date=None,
        status="Final",
        version="2.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000009": CTTermName(
        term_uid="CTTerm_000009",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Basic",
        sponsor_preferred_name_sentence_case="basic",
        order=999999,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 14, 11, 18, 0, 412149),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000005": CTTermName(
        term_uid="CTTerm_000005",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Dose Escalation",
        sponsor_preferred_name_sentence_case="dose escalation",
        order=999999,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 14, 11, 17, 56, 955320),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000008": CTTermName(
        term_uid="CTTerm_000008",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Elimination",
        sponsor_preferred_name_sentence_case="elimination",
        order=999999,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 14, 11, 17, 59, 531881),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000007": CTTermName(
        term_uid="CTTerm_000007",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Extension",
        sponsor_preferred_name_sentence_case="extension",
        order=999999,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 14, 11, 17, 58, 225190),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "C125938_BASELINE": CTTermName(
        term_uid="C125938_BASELINE",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Baseline Epoch",
        sponsor_preferred_name_sentence_case="baseline epoch",
        order=None,
        library_name="CDISC",
        start_date=datetime.datetime(2022, 7, 14, 10, 13, 3, 691000),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Initial import from CDISC",
        user_initials="IMPORT",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000227": CTTermName(
        term_uid="CTTerm_000227",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Follow-up 2",
        sponsor_preferred_name_sentence_case="follow-up 2",
        order=None,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 28, 15, 52, 0, 906334),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000226": CTTermName(
        term_uid="CTTerm_000226",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Treatment 1",
        sponsor_preferred_name_sentence_case="treatment 1",
        order=None,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 18, 8, 29, 55, 225665),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
    "CTTerm_000225": CTTermName(
        term_uid="CTTerm_000225",
        catalogue_name="SDTM CT",
        codelist_uid="C99079",
        sponsor_preferred_name="Treatment 2",
        sponsor_preferred_name_sentence_case="treatment 2",
        order=None,
        library_name="Sponsor",
        start_date=datetime.datetime(2022, 7, 18, 8, 29, 44, 513681),
        end_date=None,
        status="Final",
        version="1.0",
        change_description="Approved version",
        user_initials="unknown-user",
        possible_actions=["inactivate", "new_version"],
    ),
}

STUDY_ACTIVITIES = GenericFilteringReturn.create(
    items=[
        StudySelectionActivity(
            study_uid="Study_000001",
            order=1,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000001",
            activity=Activity(
                uid="Activity_001751",
                name="RANDOMIZED",
                name_sentence_case="RANDOMIZED",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 9, 4, 9, 998719),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 12, 818790),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=2,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000002",
            activity=Activity(
                uid="Activity_000546",
                name="End of Study",
                name_sentence_case="End of Study",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 57, 4, 795635),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 13, 751986),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=3,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000003",
            activity=Activity(
                uid="Activity_001597",
                name="Physical Examination",
                name_sentence_case="Physical Examination",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 9, 3, 5, 494794),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000040", name="Physical Examination"
                ),
                activity_group=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 14, 660394),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=4,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000004",
            activity=Activity(
                uid="Activity_001183",
                name="Medical History/Concomitant Illness",
                name_sentence_case="Medical History/Concomitant Illness",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 9, 0, 24, 221859),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 15, 486565),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=5,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000005",
            activity=Activity(
                uid="Activity_001040",
                name="INFORMED CONSENT OBTAINED",
                name_sentence_case="INFORMED CONSENT OBTAINED",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 59, 38, 371600),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 16, 48140),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=6,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000006",
            activity=Activity(
                uid="Activity_000444",
                name="Date of Birth",
                name_sentence_case="Date of Birth",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 56, 36, 788634),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 16, 646715),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=7,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000007",
            activity=Activity(
                uid="Activity_000561",
                name="Ethnicity",
                name_sentence_case="Ethnicity",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 57, 8, 594075),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 17, 261574),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=8,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000008",
            activity=Activity(
                uid="Activity_001749",
                name="Race",
                name_sentence_case="Race",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 9, 4, 9, 118136),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 17, 884257),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=9,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000009",
            activity=Activity(
                uid="Activity_001770",
                name="Sex",
                name_sentence_case="Sex",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 9, 4, 18, 506037),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000074",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SUBJECT RELATED INFORMATION",
                sponsor_preferred_name_sentence_case="subject related information",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 18, 501300),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=10,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000010",
            activity=Activity(
                uid="Activity_000289",
                name="Weight",
                name_sentence_case="Weight",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 55, 59, 716800),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000038", name="Body Measurements"
                ),
                activity_group=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000065",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SAFETY",
                sponsor_preferred_name_sentence_case="safety",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 26, 286875),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 19, 539906),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=11,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000011",
            activity=Activity(
                uid="Activity_000721",
                name="Height",
                name_sentence_case="Height",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 57, 51, 150408),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000038", name="Body Measurements"
                ),
                activity_group=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000065",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="SAFETY",
                sponsor_preferred_name_sentence_case="safety",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 26, 286875),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 20, 327068),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
        StudySelectionActivity(
            study_uid="Study_000001",
            order=12,
            project_number=None,
            project_name=None,
            show_activity_group_in_protocol_flowchart=True,
            show_activity_subgroup_in_protocol_flowchart=True,
            show_activity_in_protocol_flowchart=False,
            study_activity_uid="StudyActivity_000012",
            activity=Activity(
                uid="Activity_000631",
                name="Mean Glucose Plasma Fasting",
                name_sentence_case="Mean Glucose Plasma Fasting",
                definition=None,
                abbreviation=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 16, 8, 57, 26, 962592),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
                activity_subgroup=None,
                activity_group=None,
            ),
            flowchart_group=CTTermName(
                term_uid="CTTerm_000067",
                catalogue_name="SDTM CT",
                codelist_uid="CTCodelist_000020",
                sponsor_preferred_name="EFFICACY",
                sponsor_preferred_name_sentence_case="efficacy",
                order=None,
                library_name="Sponsor",
                start_date=datetime.datetime(2022, 7, 14, 11, 18, 26, 537862),
                end_date=None,
                status="Final",
                version="1.0",
                change_description="Approved version",
                user_initials="unknown-user",
                possible_actions=["inactivate", "new_version"],
            ),
            note=None,
            start_date=datetime.datetime(2022, 7, 22, 9, 57, 21, 444306),
            user_initials="unknown-user",
            end_date=None,
            status=None,
            change_type=None,
            latest_activity=None,
            accepted_version=False,
        ),
    ],
    total_count=0,
)

TABLE = TableWithHeaders(
    headers=[
        TableHeader(
            data=[
                "header1",
                "Study epoch",
                "Screening",
                "Treatment",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Extension",
                "Follow-up",
                "Elimination",
            ],
            spans=[1, 1, 1, 8, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header2",
                "Visit short name",
                "V1",
                "V2",
                "V3",
                "V4",
                "V5",
                "V6",
                "V7",
                "V8",
                "V9 - V10",
                "V11",
                "V12",
                "P13",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header3",
                "Study day",
                "-14",
                "1",
                "8",
                "15",
                "22",
                "29",
                "36",
                "43",
                "50-57",
                "64",
                "183",
                "366",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header4",
                "Visit window (days)",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
    ],
    data=[
        [
            "fchGroup",
            "SUBJECT RELATED INFORMATION",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["group", "Examinations", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
            "subGroup",
            "Physical Examination",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["fchGroup", "SAFETY", "", "", "", "", "", "", "", "", "", "", "", ""],
        ["group", "Examinations", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
            "subGroup",
            "Body Measurements",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["fchGroup", "EFFICACY", "", "", "", "", "", "", "", "", "", "", "", ""],
    ],
)


class MockStudyFlowchartService(StudyFlowchartService):
    @property
    def epoch_terms(self):
        return EPOCH_TERMS

    def get_study_visits(self, *_args, **_kwargs):
        return STUDY_VISITS.items

    def get_study_activities(self, *_args, **_kwargs):
        return STUDY_ACTIVITIES.items


# pylint: disable=redefined-outer-name
@pytest.fixture(scope="module")
def study_flowchart_service():
    return MockStudyFlowchartService(USER_INITIALS)


def test_iter_visits_grouped(study_flowchart_service):
    study_visits = study_flowchart_service.get_study_visits("")
    study_visits_grouped = list(
        study_flowchart_service.iter_visits_grouped(study_visits)
    )
    assert (
        len(study_visits_grouped) == len(study_visits) - 1
    ), "Unexpected number of visit groups"
    for v in study_visits_grouped:
        assert v, "empty visit group"
        assert v[0], "false visit in group"
        assert isinstance(v[0], StudyVisit), "visit in group is not a StudyVisit"


def test_get_table_headers(study_flowchart_service):
    study_visits = study_flowchart_service.get_study_visits("")
    study_visits_grouped = study_flowchart_service.iter_visits_grouped(study_visits)
    headers = study_flowchart_service.get_table_headers(study_visits_grouped, "days")
    assert headers == TABLE.headers, "table headers mismatch"


def test_get_table(study_flowchart_service):
    table = study_flowchart_service.get_table("", "days")
    assert table.headers == TABLE.headers, "table headers mismatch"
    assert table.data == TABLE.data, "table data mismatch"


def test_get_html_document(study_flowchart_service):
    table = study_flowchart_service.get_table("", "")
    assert table.data and table.data[1]

    html = study_flowchart_service.get_html_document("", "")

    # Check that document is HTML and has table data (not only headers)
    assert "</body>" in html, "document has no </body>"
    assert "</td>" in html, "document has no </td>"

    assert_table_data_in_str(table, html)

    html = BeautifulSoup(html, features="lxml")
    h_table = html.find("table")
    assert h_table, "TABLE tag not found in document"

    h_trs = h_table.findAll("tr")
    assert h_trs, "no TR tag found in document"
    assert len(h_trs) >= len(table.headers), "too few TR tags in document"

    for i, header in enumerate(table.headers):
        h_tds = h_trs[i].findAll(["th", "td"])
        if len(h_tds) < len(list(filter(None, header.spans[1:]))):
            assert f"too few TH/TD tags in header #{i}"
        for h_td, span in zip(h_tds, filter(None, header.spans[1:])):
            colspan = h_td.get("colspan", 1)
            assert int(colspan) == span, f"colspan mismatch in header row #{i}"


def test_get_docx_document(study_flowchart_service):
    table = study_flowchart_service.get_table("", "")
    assert table.data and table.data[1]

    cols = len(table.headers[-1].data) - 1
    rows = len(table.headers) + len(table.data)

    docx = study_flowchart_service.get_docx_document("", "").document

    assert len(docx.tables) == 1, "expected exactly 1 table in DOCX document"

    docx_table = docx.tables[0]
    assert len(docx_table.columns) == cols, f"expected {cols} columns of table"
    assert len(docx_table.rows) == rows, f"expected {rows} rows of table"

    # extract all text from the table
    doc = "\n".join([cell.text for row in docx_table.rows for cell in row.cells])

    assert_table_data_in_str(table, doc)


def assert_table_data_in_str(table, doc):
    """ensure that textual contents of table is present in a string"""

    for header in table.headers:
        for txt in header.data[1:]:
            if txt:
                assert txt in doc, f'text "{txt}" was not found in document'

    for row in table.data:
        assert row[1] in doc, f'text "{row[1]}" was not found in document'
