import datetime

import pytest

from clinical_mdr_api.models import (
    Activity,
    CTTermName,
    StudySelectionActivity,
    StudyVisit,
)
from clinical_mdr_api.models.activities.activity import ActivityHierarchySimpleModel
from clinical_mdr_api.models.table_with_headers import TableHeader, TableWithHeaders
from clinical_mdr_api.models.utils import GenericFilteringReturn
from clinical_mdr_api.services.study_flowchart import StudyFlowchartService

USER_INITIALS = "unknown-user"

STUDY_VISITS = GenericFilteringReturn.create(
    items=[
        StudyVisit(
            study_epoch_uid="StudyEpoch_000001",
            visitTypeUid="CTTerm_000171",
            timeReferenceUid="CTTerm_000117",
            timeValue=-2,
            timeUnitUid="UnitDefinition_000171",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000021",
            studyUid="Study_000001",
            studyEpochName="Screening",
            epochUid="C48262_SCREENING",
            order=1,
            visitTypeName="Screening",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="weeks",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=-1209600.0,
            durationTimeUnit="UnitDefinition_000171",
            studyDayNumber=-14,
            studyDurationDaysLabel="-15 days",
            studyDayLabel="Day -14",
            studyWeekNumber=-2,
            studyDurationWeeksLabel="-3 weeks",
            studyWeekLabel="Week -2",
            visit_number=1,
            visitSubNumber=0,
            unique_visit_number=100,
            visitSubName="Visit 1",
            visit_sub_label=None,
            visitName="Visit 1",
            visitShortName="V1",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:48",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=0,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=True,
            uid="StudyVisit_000022",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=2,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=0.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=1,
            studyDurationDaysLabel="0 days",
            studyDayLabel="Day 1",
            studyWeekNumber=1,
            studyDurationWeeksLabel="0 weeks",
            studyWeekLabel="Week 1",
            visit_number=2,
            visitSubNumber=0,
            unique_visit_number=200,
            visitSubName="Visit 2",
            visit_sub_label=None,
            visitName="Visit 2",
            visitShortName="V2",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:49",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=7,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000023",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=3,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=604800.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=8,
            studyDurationDaysLabel="7 days",
            studyDayLabel="Day 8",
            studyWeekNumber=2,
            studyDurationWeeksLabel="1 weeks",
            studyWeekLabel="Week 2",
            visit_number=3,
            visitSubNumber=0,
            unique_visit_number=300,
            visitSubName="Visit 3",
            visit_sub_label=None,
            visitName="Visit 3",
            visitShortName="V3",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:49",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=14,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000024",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=4,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=1209600.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=15,
            studyDurationDaysLabel="14 days",
            studyDayLabel="Day 15",
            studyWeekNumber=3,
            studyDurationWeeksLabel="2 weeks",
            studyWeekLabel="Week 3",
            visit_number=4,
            visitSubNumber=0,
            unique_visit_number=400,
            visitSubName="Visit 4",
            visit_sub_label=None,
            visitName="Visit 4",
            visitShortName="V4",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:49",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=21,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000025",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=5,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=1814400.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=22,
            studyDurationDaysLabel="21 days",
            studyDayLabel="Day 22",
            studyWeekNumber=4,
            studyDurationWeeksLabel="3 weeks",
            studyWeekLabel="Week 4",
            visit_number=5,
            visitSubNumber=0,
            unique_visit_number=500,
            visitSubName="Visit 5",
            visit_sub_label=None,
            visitName="Visit 5",
            visitShortName="V5",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:50",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=28,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000026",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=6,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=2419200.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=29,
            studyDurationDaysLabel="28 days",
            studyDayLabel="Day 29",
            studyWeekNumber=5,
            studyDurationWeeksLabel="4 weeks",
            studyWeekLabel="Week 5",
            visit_number=6,
            visitSubNumber=0,
            unique_visit_number=600,
            visitSubName="Visit 6",
            visit_sub_label=None,
            visitName="Visit 6",
            visitShortName="V6",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:50",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=35,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000027",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=7,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=3024000.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=36,
            studyDurationDaysLabel="35 days",
            studyDayLabel="Day 36",
            studyWeekNumber=6,
            studyDurationWeeksLabel="5 weeks",
            studyWeekLabel="Week 6",
            visit_number=7,
            visitSubNumber=0,
            unique_visit_number=700,
            visitSubName="Visit 7",
            visit_sub_label=None,
            visitName="Visit 7",
            visitShortName="V7",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:50",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=42,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000028",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=8,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=3628800.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=43,
            studyDurationDaysLabel="42 days",
            studyDayLabel="Day 43",
            studyWeekNumber=7,
            studyDurationWeeksLabel="6 weeks",
            studyWeekLabel="Week 7",
            visit_number=8,
            visitSubNumber=0,
            unique_visit_number=800,
            visitSubName="Visit 8",
            visit_sub_label=None,
            visitName="Visit 8",
            visitShortName="V8",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:50",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=49,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000029",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=9,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=4233600.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=50,
            studyDurationDaysLabel="49 days",
            studyDayLabel="Day 50",
            studyWeekNumber=8,
            studyDurationWeeksLabel="7 weeks",
            studyWeekLabel="Week 8",
            visit_number=9,
            visitSubNumber=0,
            unique_visit_number=900,
            visitSubName="Visit 9",
            visit_sub_label=None,
            visitName="Visit 9",
            visitShortName="V9",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:50",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000002",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000117",
            timeValue=56,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000030",
            studyUid="Study_000001",
            studyEpochName="Treatment",
            epochUid="C101526_TREATMENT",
            order=10,
            visitTypeName="Treatment",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=4838400.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=57,
            studyDurationDaysLabel="56 days",
            studyDayLabel="Day 57",
            studyWeekNumber=9,
            studyDurationWeeksLabel="8 weeks",
            studyWeekLabel="Week 9",
            visit_number=10,
            visitSubNumber=0,
            unique_visit_number=1000,
            visitSubName="Visit 10",
            visit_sub_label=None,
            visitName="Visit 10",
            visitShortName="V10",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-24 11:52:51",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000042",
            visitTypeUid="CTTerm_000176",
            timeReferenceUid="CTTerm_000113",
            timeValue=1,
            timeUnitUid="UnitDefinition_000166",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000044",
            studyUid="Study_000001",
            studyEpochName="Extension",
            epochUid="CTTerm_000007",
            order=11,
            visitTypeName="Treatment",
            timeReferenceName="Previous Visit",
            timeUnitName="week",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=5443200.0,
            durationTimeUnit="UnitDefinition_000166",
            studyDayNumber=64,
            studyDurationDaysLabel="7 days",
            studyDayLabel="Day 64",
            studyWeekNumber=10,
            studyDurationWeeksLabel="1 weeks",
            studyWeekLabel="Week 10",
            visit_number=11,
            visitSubNumber=0,
            unique_visit_number=1100,
            visitSubName="Visit 11",
            visit_sub_label=None,
            visitName="Visit 11",
            visitShortName="V11",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-26 02:14:58",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000003",
            visitTypeUid="CTTerm_000161",
            timeReferenceUid="CTTerm_000117",
            timeValue=182,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000080",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000031",
            studyUid="Study_000001",
            studyEpochName="Follow-up",
            epochUid="C99158_FOLLOW-UP",
            order=12,
            visitTypeName="Follow-up",
            timeReferenceName="Global Anchor Visit",
            timeUnitName="days",
            visitContactModeName="On Site Visit",
            epochAllocationName=None,
            durationTime=15724800.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=183,
            studyDurationDaysLabel="182 days",
            studyDayLabel="Day 183",
            studyWeekNumber=27,
            studyDurationWeeksLabel="26 weeks",
            studyWeekLabel="Week 27",
            visit_number=12,
            visitSubNumber=0,
            unique_visit_number=1200,
            visitSubName="Visit 12",
            visit_sub_label=None,
            visitName="Visit 12",
            visitShortName="V12",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-08-26 02:14:31",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
        StudyVisit(
            study_epoch_uid="StudyEpoch_000034",
            visitTypeUid="CTTerm_000164",
            timeReferenceUid="CTTerm_000113",
            timeValue=183,
            timeUnitUid="UnitDefinition_000151",
            visitSubLabelCodelistUid=None,
            visitSubLabelReference=None,
            legacyVisitId=None,
            legacyVisitTypeAlias=None,
            legacyName=None,
            legacySubName=None,
            consecutiveVisitGroup=None,
            show_visit=True,
            minVisitWindowValue=0,
            maxVisitWindowValue=0,
            visitWindowUnitUid="UnitDefinition_000151",
            description=None,
            startRule=None,
            endRule=None,
            note=None,
            visitContactModeUid="CTTerm_000079",
            epochAllocationUid=None,
            visitClass="SINGLE_VISIT",
            visitSubclass="SINGLE_VISIT",
            isGlobalAnchorVisit=False,
            uid="StudyVisit_000045",
            studyUid="Study_000001",
            studyEpochName="Elimination",
            epochUid="CTTerm_000008",
            order=13,
            visitTypeName="Post treatment activity",
            timeReferenceName="Previous Visit",
            timeUnitName="days",
            visitContactModeName="Phone Contact",
            epochAllocationName=None,
            durationTime=31536000.0,
            durationTimeUnit="UnitDefinition_000151",
            studyDayNumber=366,
            studyDurationDaysLabel="183 days",
            studyDayLabel="Day 366",
            studyWeekNumber=53,
            studyDurationWeeksLabel="26 weeks",
            studyWeekLabel="Week 53",
            visit_number=13,
            visitSubNumber=0,
            unique_visit_number=1300,
            visitSubName="Visit 13",
            visit_sub_label=None,
            visitName="Visit 13",
            visitShortName="P13",
            visitWindowUnitName="days",
            status="DRAFT",
            startDate="2022-09-01 09:39:57",
            userInitials="unknown-user",
            possibleActions=["edit", "delete", "lock"],
            studyActivityCount=0,
        ),
    ],
    total_count=0,
)

EPOCH_TERMS = {
    "C48262_SCREENING": CTTermName(
        termUid="C48262_SCREENING",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Screening",
        sponsorPreferredNameSentenceCase="screening",
        order=1,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 1, 487948),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C98779_RUN-IN": CTTermName(
        termUid="C98779_RUN-IN",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Run-in",
        sponsorPreferredNameSentenceCase="run-in",
        order=2,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 2, 35843),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C101526_TREATMENT": CTTermName(
        termUid="C101526_TREATMENT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Treatment",
        sponsorPreferredNameSentenceCase="treatment",
        order=4,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 2, 582342),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C165873_OBSERVATION": CTTermName(
        termUid="C165873_OBSERVATION",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Observation",
        sponsorPreferredNameSentenceCase="observation",
        order=5,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 3, 224234),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C123453_INDUCTION TREATMENT": CTTermName(
        termUid="C123453_INDUCTION TREATMENT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Induction Therapy",
        sponsorPreferredNameSentenceCase="induction therapy",
        order=6,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 3, 857591),
        endDate=None,
        status="Final",
        version="2.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C102256_OPEN LABEL TREATMENT": CTTermName(
        termUid="C102256_OPEN LABEL TREATMENT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Open Label Treatment",
        sponsorPreferredNameSentenceCase="open label treatment",
        order=7,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 4, 455043),
        endDate=None,
        status="Final",
        version="2.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C102255_BLINDED TREATMENT": CTTermName(
        termUid="C102255_BLINDED TREATMENT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Blinded Treatment",
        sponsorPreferredNameSentenceCase="blinded treatment",
        order=8,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 5, 74978),
        endDate=None,
        status="Final",
        version="2.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C123452_CONTINUATION TREATMENT": CTTermName(
        termUid="C123452_CONTINUATION TREATMENT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Continuation Treatment",
        sponsorPreferredNameSentenceCase="continuation treatment",
        order=9,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 5, 620200),
        endDate=None,
        status="Final",
        version="2.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C42872_WASHOUT": CTTermName(
        termUid="C42872_WASHOUT",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Wash-out",
        sponsorPreferredNameSentenceCase="wash-out",
        order=10,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 6, 129830),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C99158_FOLLOW-UP": CTTermName(
        termUid="C99158_FOLLOW-UP",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Follow-up",
        sponsorPreferredNameSentenceCase="follow-up",
        order=11,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 6, 690361),
        endDate=None,
        status="Final",
        version="3.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C16032_LONG-TERM FOLLOW-UP": CTTermName(
        termUid="C16032_LONG-TERM FOLLOW-UP",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Long-term Follow-up",
        sponsorPreferredNameSentenceCase="long-term follow-up",
        order=12,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 7, 319109),
        endDate=None,
        status="Final",
        version="2.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000009": CTTermName(
        termUid="CTTerm_000009",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Basic",
        sponsorPreferredNameSentenceCase="basic",
        order=999999,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 14, 11, 18, 0, 412149),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000005": CTTermName(
        termUid="CTTerm_000005",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Dose Escalation",
        sponsorPreferredNameSentenceCase="dose escalation",
        order=999999,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 14, 11, 17, 56, 955320),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000008": CTTermName(
        termUid="CTTerm_000008",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Elimination",
        sponsorPreferredNameSentenceCase="elimination",
        order=999999,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 14, 11, 17, 59, 531881),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000007": CTTermName(
        termUid="CTTerm_000007",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Extension",
        sponsorPreferredNameSentenceCase="extension",
        order=999999,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 14, 11, 17, 58, 225190),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "C125938_BASELINE": CTTermName(
        termUid="C125938_BASELINE",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Baseline Epoch",
        sponsorPreferredNameSentenceCase="baseline epoch",
        order=None,
        libraryName="CDISC",
        startDate=datetime.datetime(2022, 7, 14, 10, 13, 3, 691000),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Initial import from CDISC",
        userInitials="IMPORT",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000227": CTTermName(
        termUid="CTTerm_000227",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Follow-up 2",
        sponsorPreferredNameSentenceCase="follow-up 2",
        order=None,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 28, 15, 52, 0, 906334),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000226": CTTermName(
        termUid="CTTerm_000226",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Treatment 1",
        sponsorPreferredNameSentenceCase="treatment 1",
        order=None,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 18, 8, 29, 55, 225665),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
    "CTTerm_000225": CTTermName(
        termUid="CTTerm_000225",
        catalogueName="SDTM CT",
        codelistUid="C99079",
        sponsorPreferredName="Treatment 2",
        sponsorPreferredNameSentenceCase="treatment 2",
        order=None,
        libraryName="Sponsor",
        startDate=datetime.datetime(2022, 7, 18, 8, 29, 44, 513681),
        endDate=None,
        status="Final",
        version="1.0",
        changeDescription="Approved version",
        userInitials="unknown-user",
        possibleActions=["inactivate", "newVersion"],
    ),
}

STUDY_ACTIVITIES = GenericFilteringReturn.create(
    items=[
        StudySelectionActivity(
            studyUid="Study_000001",
            order=1,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000001",
            activity=Activity(
                uid="Activity_001751",
                name="RANDOMIZED",
                nameSentenceCase="RANDOMIZED",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 9, 4, 9, 998719),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 12, 818790),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=2,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000002",
            activity=Activity(
                uid="Activity_000546",
                name="End of Study",
                nameSentenceCase="End of Study",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 57, 4, 795635),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 13, 751986),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=3,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000003",
            activity=Activity(
                uid="Activity_001597",
                name="Physical Examination",
                nameSentenceCase="Physical Examination",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 9, 3, 5, 494794),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000040", name="Physical Examination"
                ),
                activityGroup=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 14, 660394),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=4,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000004",
            activity=Activity(
                uid="Activity_001183",
                name="Medical History/Concomitant Illness",
                nameSentenceCase="Medical History/Concomitant Illness",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 9, 0, 24, 221859),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 15, 486565),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=5,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000005",
            activity=Activity(
                uid="Activity_001040",
                name="INFORMED CONSENT OBTAINED",
                nameSentenceCase="INFORMED CONSENT OBTAINED",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 59, 38, 371600),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 16, 48140),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=6,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000006",
            activity=Activity(
                uid="Activity_000444",
                name="Date of Birth",
                nameSentenceCase="Date of Birth",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 56, 36, 788634),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 16, 646715),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=7,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000007",
            activity=Activity(
                uid="Activity_000561",
                name="Ethnicity",
                nameSentenceCase="Ethnicity",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 57, 8, 594075),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 17, 261574),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=8,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000008",
            activity=Activity(
                uid="Activity_001749",
                name="Race",
                nameSentenceCase="Race",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 9, 4, 9, 118136),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 17, 884257),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=9,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000009",
            activity=Activity(
                uid="Activity_001770",
                name="Sex",
                nameSentenceCase="Sex",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 9, 4, 18, 506037),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000074",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SUBJECT RELATED INFORMATION",
                sponsorPreferredNameSentenceCase="subject related information",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 27, 303576),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 18, 501300),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=10,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000010",
            activity=Activity(
                uid="Activity_000289",
                name="Weight",
                nameSentenceCase="Weight",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 55, 59, 716800),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000038", name="Body Measurements"
                ),
                activityGroup=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000065",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SAFETY",
                sponsorPreferredNameSentenceCase="safety",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 26, 286875),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 19, 539906),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=11,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000011",
            activity=Activity(
                uid="Activity_000721",
                name="Height",
                nameSentenceCase="Height",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 57, 51, 150408),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=ActivityHierarchySimpleModel(
                    uid="ActivitySubGroup_000038", name="Body Measurements"
                ),
                activityGroup=ActivityHierarchySimpleModel(
                    uid="ActivityGroup_000005", name="Examinations"
                ),
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000065",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="SAFETY",
                sponsorPreferredNameSentenceCase="safety",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 26, 286875),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 20, 327068),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
        StudySelectionActivity(
            studyUid="Study_000001",
            order=12,
            projectNumber=None,
            projectName=None,
            showActivityGroupInProtocolFlowchart=True,
            showActivitySubGroupInProtocolFlowchart=True,
            showActivityInProtocolFlowchart=False,
            studyActivityUid="StudyActivity_000012",
            activity=Activity(
                uid="Activity_000631",
                name="Mean Glucose Plasma Fasting",
                nameSentenceCase="Mean Glucose Plasma Fasting",
                definition=None,
                abbreviation=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 16, 8, 57, 26, 962592),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
                activitySubGroup=None,
                activityGroup=None,
            ),
            flowchartGroup=CTTermName(
                termUid="CTTerm_000067",
                catalogueName="SDTM CT",
                codelistUid="CTCodelist_000020",
                sponsorPreferredName="EFFICACY",
                sponsorPreferredNameSentenceCase="efficacy",
                order=None,
                libraryName="Sponsor",
                startDate=datetime.datetime(2022, 7, 14, 11, 18, 26, 537862),
                endDate=None,
                status="Final",
                version="1.0",
                changeDescription="Approved version",
                userInitials="unknown-user",
                possibleActions=["inactivate", "newVersion"],
            ),
            note=None,
            startDate=datetime.datetime(2022, 7, 22, 9, 57, 21, 444306),
            userInitials="unknown-user",
            endDate=None,
            status=None,
            changeType=None,
            latestActivity=None,
            acceptedVersion=False,
        ),
    ],
    total_count=0,
)

TABLE = TableWithHeaders(
    headers=[
        TableHeader(
            data=[
                "header1",
                "Study epoch",
                "Screening",
                "Treatment",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Extension",
                "Follow-up",
                "Elimination",
            ],
            spans=[1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header2",
                "Visit short name",
                "V1",
                "V2",
                "V3",
                "V4",
                "V5",
                "V6",
                "V7",
                "V8",
                "V9",
                "V10",
                "V11",
                "V12",
                "P13",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header3",
                "Study day",
                "-14",
                "1",
                "8",
                "15",
                "22",
                "29",
                "36",
                "43",
                "50",
                "57",
                "64",
                "183",
                "366",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
        TableHeader(
            data=[
                "header4",
                "Visit window (days)",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
                "±0",
            ],
            spans=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ),
    ],
    data=[
        [
            "fchGroup",
            "SUBJECT RELATED INFORMATION",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["group", "Examinations", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
            "subGroup",
            "Physical Examination",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["fchGroup", "SAFETY", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ["group", "Examinations", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
            "subGroup",
            "Body Measurements",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        ["fchGroup", "EFFICACY", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    ],
)


class MockStudyFlowchartService(StudyFlowchartService):
    @property
    def epoch_terms(self):
        return EPOCH_TERMS

    def get_study_visits(self, *_args, **_kwargs):
        return STUDY_VISITS

    def get_study_activities(self, *_args, **_kwargs):
        return STUDY_ACTIVITIES


# pylint: disable=redefined-outer-name
@pytest.fixture(scope="module")
def study_flowchart_service():
    return MockStudyFlowchartService(USER_INITIALS)


def test_get_table_headers(study_flowchart_service):
    study_visits = study_flowchart_service.get_study_visits("").items
    headers = study_flowchart_service.get_table_headers(study_visits, "days")
    assert headers == TABLE.headers, "table headers mismatch"


def test_get_table(study_flowchart_service):
    table = study_flowchart_service.get_table("", "days")
    assert table.headers == TABLE.headers, "table headers mismatch"
    assert table.data == TABLE.data, "table data mismatch"


def test_get_html_document(study_flowchart_service):
    table = study_flowchart_service.get_table("", "")
    assert table.data and table.data[1]

    doc = study_flowchart_service.get_html_document("", "")

    # Check that document is HTML and has table data (not only headers)
    assert "</body>" in doc, "document has no </body>"
    assert "</td>" in doc, "document has no </td>"

    assert_table_data_in_document(table, doc)


def test_get_docx_document(study_flowchart_service):
    table = study_flowchart_service.get_table("", "")
    assert table.data and table.data[1]

    cols = len(table.headers[-1].data) - 1
    rows = len(table.headers) + len(table.data)

    docx = study_flowchart_service.get_docx_document("", "").document

    assert len(docx.tables) == 1, "expected exactly 1 table in DOCX document"

    docx_table = docx.tables[0]
    assert len(docx_table.columns) == cols, f"expected {cols} columns of table"
    assert len(docx_table.rows) == rows, f"expected {rows} rows of table"

    # extract all text from the table
    doc = "\n".join([cell.text for row in docx_table.rows for cell in row.cells])

    assert_table_data_in_document(table, doc)


def assert_table_data_in_document(table, doc):
    for header in table.headers:
        for txt in header.data[1:]:
            if txt:
                assert txt in doc, f'text "{txt}" was not found in document'

    for row in table.data:
        assert row[1] in doc, f'text "{row[1]}" was not found in document'
