const TYPE_OF_TREATMENT_INVESTIGATIONAL_PRODUCT = 'Investigational Product'
const TYPE_OF_TREATMENT_CURRENT_TREATMENT = 'Current Treatment'
const TYPE_OF_TREATMENT_COMPARATIVE_TREATMENT = 'Comparative Treatment'

export default {
  TYPE_OF_TREATMENT_COMPARATIVE_TREATMENT,
  TYPE_OF_TREATMENT_CURRENT_TREATMENT,
  TYPE_OF_TREATMENT_INVESTIGATIONAL_PRODUCT
}
