const TIME_UNIT_SUBSET_STUDY_TIME = 'Study Time'
const TIME_UNIT_SUBSET_STUDY_PREFERRED_TIME_UNIT = 'Study Preferred Time Unit'

export default {
  TIME_UNIT_SUBSET_STUDY_TIME,
  TIME_UNIT_SUBSET_STUDY_PREFERRED_TIME_UNIT
}
