#!/bin/bash
#
# Script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

# Check for linked work item in commit message.
# Tasks, user stories, features and enablers can all be referenced with the same syntax:
# #XYZ where XYZ is the ID number of the item in DevOps.

msg=$(cat "$1") # Grab the commit message from git

# Check if the commit message matches the right-hand regular expression (looking for # followed by one or more digits)
if [[ $msg =~ \#[0-9]+ ]]; then
	exit 0
fi

echo "Commit hook failed - no work item linked."
echo "Please make sure to add a work item via the hash character '#' in your commit message. E.g. 'Added something; #223941'"
exit 1
